### ISSUE TITLE
Speed

### ISSUE THREAD

**Issue by WhyNotAsif** [Myyepz/Sby#1]
Processes slow
Sending/Replying massages and also kicking too slow
Please resolve....
I'll appreciate

**Comment by Myyepz** [comment]
Can u Use Server Not Provider Network

**Comment by Myyepz** [comment]
Use New Versions

**Comment by WhyNotAsif** [comment]
After a year you reply
Thanks for your respon, can you please gave me your Line id , we discus there

**Comment by Myyepz** [comment]
check your connection network
